InputDataApp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'InputDataApp'

urlpatterns = [
    path('', views.inputdata, name='input_data'),

]

qna/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'question', views.QnAViewSet)

app_name = 'qna'

urlpatterns = [
    path('', views.index, name='qna'),
    path('recent/', views.index, name='recent'),
    path('router/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('ambilData/', views.getData),
]

tk1/urls.py
from django import conf
from django.conf.urls import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tk1app.urls')),
    path('input/', include('InputDataApp.urls')),
    path('daftar/', include('daftar.urls')),
    path('qna/', include('qna.urls', namespace="qna")),
    path('',include('thingsToDo.urls'))
]

urlpatterns += static.static(conf.settings.MEDIA_URL, document_root=conf.settings.MEDIA_ROOT)
urlpatterns += static.static(conf.settings.STATIC_URL, document_root=conf.settings.STATIC_ROOT)

tk1app/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home, index, func_login, func_logout

app_name = "tk1app"

urlpatterns = [
    path('', home, name= 'home'),
    path('', index, name='index'),
    path('login/', func_login, name = 'login'),
    path('logout/', func_logout, name = 'logout'),
]

InputDataApp/models.py
from django.db import models
# Create your models here.
class tempatWisata(models.Model):
 
	nama = models.CharField(max_length=50)
	tempat = models.CharField(max_length= 50)
	harga = models.CharField(max_length=50)
	musim = models.CharField(max_length =50)
	deskripsi = models.TextField(blank = False)
	# foto = models.ImageField(upload_to = 'static/images/', default = 'pic_folder/None/no-img.jpg')
	# def __unicode__(self):
	# 	return self.nama
class tempatdimau(models.Model):
	nama = models.CharField(max_length=50)

InputDataApp/forms.py
from django import forms
from .models import tempatWisata,tempatdimau
from django.forms import widgets

class ContactForm(forms.Form):
		nama=forms.CharField(
        label = 'Nama', max_length = 50, required = True,
        widget = forms.TextInput(
            attrs = {'class' : 'form-control form-control-sm', 'placeholder' : "Masukkan Nama Tempat Wisata",}),
    )
		tempat =forms.CharField(
        label = 'Lokasi', max_length = 50, required = True,
        widget = forms.TextInput(
            attrs = {'class' : 'form-control form-control-sm', 'placeholder' : "Masukkan Lokasi Tempat Wisata",}),
    )
		harga = forms.ChoiceField(
        label='Harga',
        choices=[('< Rp500.000', '< Rp 500.000'),
                ('Rp500.000-Rp1.000.000', 'Rp500.000-Rp1.000.000'),
                ('Rp1.000.000-Rp2.0000.000','Rp1.000.000-Rp2.0000.000'),
                ('Rp2.000.000-Rp3.0000.000','Rp2.000.000-Rp3.0000.000')],
        widget = forms.Select(attrs = {'class' : 'form-control', 'style': 'color: #09B291;'})
    )
		musim = forms.ChoiceField(
        label='musim',
        choices=[('Winter', 'Winter'),
                ('Summer', 'Summer'),],
        widget = forms.Select(attrs = {'class' : 'form-control', 'style': 'color: #09B291;'})
    )
		deskripsi = forms.CharField(
        label='Deskripsi Tempat Wisata',
        widget = forms.Textarea(attrs = {'class' : 'form-control','cols': 7, 'rows': 7, })
    )
		# foto= forms.ImageField(
		# 	widget =forms.FileInput(
		# 	attrs={'class': 'form-control-files'})
		# 	)
class meta:
		model = tempatWisata
		fields = ['nama','tempat','harga','musim','deskripsi']

class tempatform(forms.Form):
		nama=forms.CharField(
        label = 'Yuk, Tuliskan tempat wisata yang kamu ingin kunjungi', max_length = 50, required = True,
        widget = forms.TextInput(
            attrs = {'class' : 'form-control form-control-sm', 'placeholder' : "Tulis disini ya",}),
    )
class meta2:
		model = tempatdimau
		fields = ['nama']

InputDataApp/views.py
from django.shortcuts import render,redirect
from django.http import Http404, HttpResponse
from .models import tempatWisata, tempatdimau
from .forms import ContactForm, tempatform
from django.http import JsonResponse
# Create your views here.
def inputdata(request):
	if request.user.is_authenticated:
		if request.method == "POST":
			form = ContactForm(request.POST)
			if form.is_valid():
				model_instance = tempatWisata(
					nama = form.data['nama'],
					tempat = form.data['tempat'],
					harga = form.data['harga'],
					musim = form.data['musim'],
					deskripsi = form.data['deskripsi'],
				# 	foto = form.data['foto']
				)
				model_instance.save()
				return redirect("/daftar/")
					
		else:
			form = ContactForm()
			

		argument={
			'form': form,
			'data': tempatdimau.objects.all().values(),
		}


		return render(request, "InputData.html",argument)	
	else:
		if request.method == "POST":
			form = tempatform(request.POST)
			if form.is_valid():
				model_instance = tempatdimau(
					nama = form.data['nama']
				# 	foto = form.data['foto']
				)
				model_instance.save()
					
		else:
			form = tempatform()
		argument={
			'form': form,
			'data': tempatdimau.objects.all(), 
		}


		return render(request, "InputData.html",argument)

InputDataApp/templates/InputData.html
<!DOCTYPE html>
{% load static%}
<html lang="en"> 
<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <meta http-equiv="X-UA-Compatible" content="ie=edge">
 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
 <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
 <title>MasukanData</title>
 <link rel="icon" href ="img/instravel.png" type="image/x-icon">
 
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>
<style>
.switch input {
    position: absolute;
    opacity: 0;
}

.switch {
    display: inline-block;
    font-size: 20px; /* 1 */
    height: 1.5em;
    width: 3em;
    background: whitesmoke;
    border-radius: 1em;
}

.switch div {
    height: 1.5em;
    width: 1.5em;
    border-radius: 2em;
    background: #333333;
    box-shadow: 0 0.1em 0.3em rgba(0,0,0,0.3);
    -webkit-transition: all 300ms;
        -moz-transition: all 300ms;
            transition: all 300ms;
}

.switch input:checked + div {
    background: yellow;
    box-shadow: 0 0.1em 0.3em rgba(0,0,0,0.3);
    -webkit-transform: translate3d(100%, 0, 0);
        -moz-transform: translate3d(100%, 0, 0);
            transform: translate3d(100%, 0, 0);
}
.light{
    background-color: white;
}

.light h1{
    color: #333333;
}

/*
dark mode
*/

.dark{
    background:#1b384a;
            background-size: cover;
}

.dark div{
    color: white;
}

.dark .card-body{background: #00aced;
	border: none;
}
</style>
<body class="light">
    <div class="container">
     <div class="row" style="margin-top: 3vh;">
		<div class="col">
			<img src="{% static 'img/instravel.png'%}" class="card-img-top" style ="max-width: 30%;">
		</div>
		<div class="row text-right">  
				<div style="margin-right:10px;">
					<label id="cb" class="switch"><input type="checkbox" id="hoho"><div></div></label>
				</div>
				{% if user.is_authenticated %}
				<a style="color: red;" class="nav-link" href="{% url 'tk1app:logout' %}">SignOut <span class="sr-only">(current)</span></a>
				{%endif%}
			<a href="/daftar/"><button class="btn" type="submit" style="border-color:black; color: black;background-color: white;margin-right:6vh;border-radius: 7px;" >List Destinasi</button></a>
		</div>
	</div>
	<form method="POST" action="." style="color: #09B291;margin-top: 3vh">
		{% csrf_token %}
		{{form}}
		{% if user.is_authenticated %}
		<div class="text-right" style=" margin-top: 10px">
			<button type="submit" class="btn btn-success" style="background-color: #09B291; border-radius: 7px;">Add</button>
		</div>
		{% else %}
		<div class="text-right" style=" margin-top: 10px">
				<button type="submit" class="btn btn-success" style="background-color: #09B291; border-radius: 7px;">Add</button>
			</div>
		{% endif%}
		</form>
		{% if not user.is_authenticated %}
	   	<div class="text-center">
			   <div>
				   Jika ingin menambahkan tempat wisata baru yuk sign in
			   </div>
		<a style="color: darkturquoise;" class="nav-link"href="{% url 'tk1app:login' %}"><u>Sign In</u><span class="sr-only">(current)</span></a>
		</div>
		{% endif%}
		<div class="text-center">
				{% if data != null %}
		<h3> Daftar request dari pengunjung</h3>
		{% endif%}
	</div>
		<div class=" container text-center card-columns">
			{% for parwis in data %}
					   <div class="card">
							<div class="card-body">
							<h4 class="card-title">{{ parwis.nama }}</h4>
							</div>
							</div>
				    {% endfor %}
					</div>
	   </div>
	   
	   <script src="{% static 'js/mode.js' %}" type="text/javascript"></script>   
	</body>
</html>